package vistas;

import java.awt.Image;
import java.net.URL;
import javax.swing.ImageIcon;

/**
@author louisinette zaoral de entesano
 */
public class VistaComida extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaComida
     */
    public VistaComida() {
        initComponents();
       colocarIconos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btAgregar = new javax.swing.JButton();
        jbModificar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        btHabilitarLista = new javax.swing.JButton();
        lbSelectTabla = new javax.swing.JLabel();
        lbHabilitada = new javax.swing.JLabel();
        txNombre = new javax.swing.JTextField();
        txIdComida = new javax.swing.JTextField();
        txReceta = new javax.swing.JTextField();
        lbIdComida = new javax.swing.JLabel();
        lbkcal = new javax.swing.JLabel();
        lbCantidadCaloriasMenor = new javax.swing.JLabel();
        rbHabilitada = new javax.swing.JRadioButton();
        rbDeshabilitada = new javax.swing.JRadioButton();
        lbDeshabilitada = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbComidas = new javax.swing.JTable();
        btBuscar = new javax.swing.JButton();
        lbingrediente = new javax.swing.JLabel();
        LbNombre = new javax.swing.JLabel();
        btNueva = new javax.swing.JButton();
        txKcal = new javax.swing.JTextField();
        lbBuscar = new javax.swing.JLabel();
        btDeshabilitarLista = new javax.swing.JButton();
        lbLimpiar = new javax.swing.JLabel();
        lbAhora = new javax.swing.JLabel();
        btLimpiar = new javax.swing.JButton();
        lbPeso = new javax.swing.JLabel();
        txPeso = new javax.swing.JTextField();
        lbGramos = new javax.swing.JLabel();
        lbAgregar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbAgregar1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lbBuscar1 = new javax.swing.JLabel();
        lbBuscar2 = new javax.swing.JLabel();
        lbBuscar3 = new javax.swing.JLabel();
        lbAgregar2 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        lbBuscar4 = new javax.swing.JLabel();
        lbAgregar3 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Gestion de Comidas");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Comidas.png"))); // NOI18N
        setPreferredSize(new java.awt.Dimension(1350, 680));
        setVerifyInputWhenFocusTarget(false);

        jPanel1.setBackground(new java.awt.Color(55, 55, 255));
        jPanel1.setForeground(java.awt.Color.white);
        jPanel1.setToolTipText("");
        jPanel1.setMinimumSize(new java.awt.Dimension(1600, 683));
        jPanel1.setPreferredSize(new java.awt.Dimension(1600, 683));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btAgregar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btAgregar.setText("Guardar");
        jPanel1.add(btAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 570, 150, 40));

        jbModificar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbModificar.setText("Modificar");
        jPanel1.add(jbModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 440, -1, 40));

        jbSalir.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jbSalir.setText("Salir");
        jPanel1.add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 570, 130, 40));

        btHabilitarLista.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btHabilitarLista.setText("Habilitar");
        jPanel1.add(btHabilitarLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 440, 150, 40));

        lbSelectTabla.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbSelectTabla.setForeground(new java.awt.Color(62, 242, 146));
        lbSelectTabla.setText("Seleccione info de la tabla y presione una opción del menu:");
        jPanel1.add(lbSelectTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, -1, -1));

        lbHabilitada.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbHabilitada.setForeground(java.awt.Color.white);
        lbHabilitada.setText("Habilitada");
        jPanel1.add(lbHabilitada, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        txNombre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 324, 30));

        txIdComida.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txIdComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 57, 30));

        txReceta.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txReceta, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 230, 30));

        lbIdComida.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbIdComida.setForeground(java.awt.Color.white);
        lbIdComida.setText("Id de Comida:");
        jPanel1.add(lbIdComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        lbkcal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbkcal.setForeground(java.awt.Color.white);
        lbkcal.setText("Kilocalorias");
        jPanel1.add(lbkcal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));

        lbCantidadCaloriasMenor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbCantidadCaloriasMenor.setForeground(java.awt.Color.white);
        lbCantidadCaloriasMenor.setText("Cantidad menor a: ");
        jPanel1.add(lbCantidadCaloriasMenor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        rbHabilitada.setBackground(new java.awt.Color(51, 51, 255));
        rbHabilitada.setForeground(new java.awt.Color(51, 51, 255));
        rbHabilitada.setBorder(null);
        rbHabilitada.setMaximumSize(new java.awt.Dimension(25, 25));
        jPanel1.add(rbHabilitada, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 30, -1));

        rbDeshabilitada.setBackground(new java.awt.Color(51, 51, 255));
        rbDeshabilitada.setBorder(null);
        rbDeshabilitada.setMaximumSize(new java.awt.Dimension(25, 25));
        jPanel1.add(rbDeshabilitada, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, -1, -1));

        lbDeshabilitada.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbDeshabilitada.setForeground(java.awt.Color.white);
        lbDeshabilitada.setText("Deshabilitada");
        jPanel1.add(lbDeshabilitada, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        tbComidas.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tbComidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbComidas.setRowHeight(18);
        tbComidas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbComidas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 710, 350));

        btBuscar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 130, 40));

        lbingrediente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbingrediente.setForeground(java.awt.Color.white);
        lbingrediente.setText("Ingrediente de la receta:");
        jPanel1.add(lbingrediente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        LbNombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LbNombre.setForeground(java.awt.Color.white);
        LbNombre.setText("Nombre:");
        jPanel1.add(LbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        btNueva.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btNueva.setText("Nueva");
        btNueva.setMaximumSize(new java.awt.Dimension(83, 31));
        btNueva.setMinimumSize(new java.awt.Dimension(83, 31));
        btNueva.setName(""); // NOI18N
        btNueva.setPreferredSize(new java.awt.Dimension(83, 31));
        jPanel1.add(btNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 460, 130, 40));

        txKcal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txKcal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 70, 30));

        lbBuscar.setBackground(java.awt.Color.white);
        lbBuscar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbBuscar.setForeground(new java.awt.Color(64, 242, 146));
        lbBuscar.setText("ó ingrese una opción de busqueda a la vez:");
        jPanel1.add(lbBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        btDeshabilitarLista.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btDeshabilitarLista.setText("Deshabilitar");
        jPanel1.add(btDeshabilitarLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 440, 180, 40));

        lbLimpiar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbLimpiar.setForeground(new java.awt.Color(62, 242, 146));
        lbLimpiar.setText("todas las opciones");
        jPanel1.add(lbLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 570, -1, -1));

        lbAhora.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbAhora.setForeground(new java.awt.Color(64, 242, 146));
        lbAhora.setText(" 2. Presione aqui");
        jPanel1.add(lbAhora, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        btLimpiar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btLimpiar.setText("Reset");
        jPanel1.add(btLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 550, 130, 40));

        lbPeso.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbPeso.setForeground(java.awt.Color.white);
        lbPeso.setText("Peso: ");
        jPanel1.add(lbPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        txPeso.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txPesoActionPerformed(evt);
            }
        });
        jPanel1.add(txPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 70, 30));

        lbGramos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbGramos.setForeground(java.awt.Color.white);
        lbGramos.setText("gramos");
        jPanel1.add(lbGramos, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, -1));

        lbAgregar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbAgregar.setForeground(new java.awt.Color(62, 242, 146));
        lbAgregar.setText("también selecciona un estado");
        jPanel1.add(lbAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 520, 10));

        lbAgregar1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbAgregar1.setForeground(new java.awt.Color(62, 242, 146));
        lbAgregar1.setText("1. Para agregar una comida presione");
        jPanel1.add(lbAgregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, 10, 190));

        lbBuscar1.setBackground(java.awt.Color.white);
        lbBuscar1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbBuscar1.setForeground(new java.awt.Color(64, 242, 146));
        lbBuscar1.setText("1. Seleccione un estado:");
        jPanel1.add(lbBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        lbBuscar2.setBackground(java.awt.Color.white);
        lbBuscar2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbBuscar2.setForeground(java.awt.Color.white);
        lbBuscar2.setText("BORRAR");
        jPanel1.add(lbBuscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 540, -1, -1));

        lbBuscar3.setBackground(java.awt.Color.white);
        lbBuscar3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbBuscar3.setForeground(java.awt.Color.white);
        lbBuscar3.setText("BUSCAR");
        jPanel1.add(lbBuscar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        lbAgregar2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbAgregar2.setForeground(new java.awt.Color(62, 242, 146));
        lbAgregar2.setText("2. Complete todas las opciones de busqueda arriba y ");
        jPanel1.add(lbAgregar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, 720, 30));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 10, 370));

        lbBuscar4.setBackground(java.awt.Color.white);
        lbBuscar4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbBuscar4.setForeground(java.awt.Color.white);
        lbBuscar4.setText("AGREGAR");
        jPanel1.add(lbBuscar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, -1, -1));

        lbAgregar3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbAgregar3.setForeground(new java.awt.Color(62, 242, 146));
        lbAgregar3.setText("3. Presione aqui");
        jPanel1.add(lbAgregar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1600, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btBuscarActionPerformed

    private void txPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txPesoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbNombre;
    public javax.swing.JButton btAgregar;
    public javax.swing.JButton btBuscar;
    public javax.swing.JButton btDeshabilitarLista;
    public javax.swing.JButton btHabilitarLista;
    public javax.swing.JButton btLimpiar;
    public javax.swing.JButton btNueva;
    public javax.swing.ButtonGroup buttonGroup;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    public javax.swing.JButton jbModificar;
    public javax.swing.JButton jbSalir;
    private javax.swing.JLabel lbAgregar;
    private javax.swing.JLabel lbAgregar1;
    private javax.swing.JLabel lbAgregar2;
    private javax.swing.JLabel lbAgregar3;
    private javax.swing.JLabel lbAhora;
    private javax.swing.JLabel lbBuscar;
    private javax.swing.JLabel lbBuscar1;
    private javax.swing.JLabel lbBuscar2;
    private javax.swing.JLabel lbBuscar3;
    private javax.swing.JLabel lbBuscar4;
    private javax.swing.JLabel lbCantidadCaloriasMenor;
    private javax.swing.JLabel lbDeshabilitada;
    private javax.swing.JLabel lbGramos;
    private javax.swing.JLabel lbHabilitada;
    private javax.swing.JLabel lbIdComida;
    private javax.swing.JLabel lbLimpiar;
    private javax.swing.JLabel lbPeso;
    private javax.swing.JLabel lbSelectTabla;
    private javax.swing.JLabel lbingrediente;
    private javax.swing.JLabel lbkcal;
    public javax.swing.JRadioButton rbDeshabilitada;
    public javax.swing.JRadioButton rbHabilitada;
    public javax.swing.JTable tbComidas;
    public javax.swing.JTextField txIdComida;
    public javax.swing.JTextField txKcal;
    public javax.swing.JTextField txNombre;
    public javax.swing.JTextField txPeso;
    public javax.swing.JTextField txReceta;
    // End of variables declaration//GEN-END:variables

private void colocarIconos(){
        int alto = 30;
        int ancho = 30; 
        
        btNueva.setIcon(prepararIcono("nuevo.png",alto,ancho));
        btAgregar.setIcon(prepararIcono("salvado.png",alto,ancho));
        btBuscar.setIcon(prepararIcono("Lupa-buscar.png",alto,ancho));
        jbSalir.setIcon(prepararIcono("salida3.png",alto,ancho));
        btHabilitarLista.setIcon(prepararIcono("activo.png",alto,ancho));
        btDeshabilitarLista.setIcon(prepararIcono("inactivo.png",alto,ancho));
        jbModificar.setIcon(prepararIcono("pencil-png-653.png",alto,ancho));
        btLimpiar.setIcon(prepararIcono("eraser.png",alto,ancho));
        ImageIcon icono = new ImageIcon();
        icono = prepararIcono("IconoFormulario.jpg",20,20);
        this.setFrameIcon(icono);
    }
    
    private ImageIcon prepararIcono(String nombre, int alto, int ancho) { // Aplicacion que prepara los Iconos para ser puestos 
        //donde se quiera se pasa el nombre y el tamaño que quieres que tenga
        // Obtener la ruta relativa a la ubicación de la clase Controlador eso es la carpeta SRC del proyecto ese seria la carpeta 
        // de inicio
        ClassLoader directorio = getClass().getClassLoader();
        URL imagen = directorio.getResource("iconos/" + nombre); // Creamos la ruta al recurso en este caso el icono de lupa
        // Crea un ImageIcon utilizando la URL de la imagen
        ImageIcon icono = new ImageIcon(imagen); // creamos la Imagen Icono para asignarsela al contenerdor
        // Redimensionar el icono pasandolo a imagen con el nuevo tamaño y luego convirtiendolo en icono XD
        Image imagenRedimensionada = icono.getImage().getScaledInstance(alto, ancho, Image.SCALE_SMOOTH);
        icono = new ImageIcon(imagenRedimensionada);
        return icono;
    }
}
