/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

/**
 *
 * @author Dario
 */
public class VistaControl extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaControl
     */
    public VistaControl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbPacientes = new javax.swing.JComboBox<>();
        btEliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        dcFecha = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        txPeso = new utilidades.MiCampoTexto(3);
        ;
        jLabel4 = new javax.swing.JLabel();
        txAltura = new utilidades.MiCampoTexto(3);
        ;
        jLabel5 = new javax.swing.JLabel();
        txCintura = new utilidades.MiCampoTexto(3);
        ;
        jLabel6 = new javax.swing.JLabel();
        txGasto = new utilidades.MiCampoTexto(3);
        ;
        txIMC = new utilidades.MiCampoTexto(3);
        ;
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dcCita = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txObs = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbControl = new javax.swing.JTable();
        btNuevo = new javax.swing.JButton();
        btGuardar = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel1.setText("Fecha");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 56, -1));

        cbPacientes.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jPanel1.add(cbPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 399, -1));

        btEliminar.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btEliminar.setText("Eliminar");
        jPanel1.add(btEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 156, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel2.setText("Paciente");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        dcFecha.setFocusable(false);
        dcFecha.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jPanel1.add(dcFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 209, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel3.setText("Peso");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txPeso.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txPeso.setText("0.00");
        jPanel1.add(txPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 103, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel4.setText("Altura");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, -1, -1));

        txAltura.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txAltura.setText("0.00");
        jPanel1.add(txAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 103, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel5.setText("Cintura");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        txCintura.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txCintura.setText("0.00");
        jPanel1.add(txCintura, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 103, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel6.setText("Gasto Energetico");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 143, -1));

        txGasto.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txGasto.setText("0.00");
        jPanel1.add(txGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 103, -1));

        txIMC.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txIMC.setText("0.00");
        txIMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txIMCActionPerformed(evt);
            }
        });
        jPanel1.add(txIMC, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 103, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel7.setText("IMC");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 35, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel8.setText("Proxima Cita");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 110, -1));

        dcCita.setFocusable(false);
        dcCita.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jPanel1.add(dcCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 209, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel9.setText("Observaciones");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 159, -1));

        txObs.setColumns(20);
        txObs.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txObs.setRows(5);
        jScrollPane1.setViewportView(txObs);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 483, 340));

        tbControl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbControl);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 0, 493, 650));

        btNuevo.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btNuevo.setText("Nuevo");
        jPanel1.add(btNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 156, -1));

        btGuardar.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btGuardar.setText("Guardar");
        jPanel1.add(btGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 156, -1));

        btSalir.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btSalir.setText("Salir");
        jPanel1.add(btSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 156, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txIMCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txIMCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btEliminar;
    public javax.swing.JButton btGuardar;
    public javax.swing.JButton btNuevo;
    public javax.swing.JButton btSalir;
    public javax.swing.JComboBox<String> cbPacientes;
    public com.toedter.calendar.JDateChooser dcCita;
    public com.toedter.calendar.JDateChooser dcFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable tbControl;
    public javax.swing.JTextField txAltura;
    public javax.swing.JTextField txCintura;
    public javax.swing.JTextField txGasto;
    public javax.swing.JTextField txIMC;
    public javax.swing.JTextArea txObs;
    public javax.swing.JTextField txPeso;
    // End of variables declaration//GEN-END:variables
}
